### ISSUE TITLE
records with spaces are modified every run

### ISSUE THREAD

**Issue by BlinkyStitt** [DNSMadeEasy/terraform-provider-dme#9]
### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
Please list the resources as a list, for example:
- dme_record

### Terraform Configuration Files
```hcl
resource "dme_record" "stitthappens_com_TXT_spf" {
  domainid    = "${var.dme_stitthappens_com}"
  name        = ""
  type        = "TXT"
  value       = "v=spf1 include:_spf.google.com ~all"
  ttl         = 86400
  gtdLocation = "DEFAULT"
}
```

### Debug Output
```
dme_record.stitthappens_com_TXT_spf: Modifying... (ID: 58119505)
  ttl:   "3600" => "86400"
  value: "\"v=spf1 include:_spf.google.com ~all\"" => "v=spf1 include:_spf.google.com ~all"
```

### Expected Behavior
The name should not update if the only difference is quoting

### Actual Behavior
Every run tries to update the record.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
I asked support for help with this issue, but they said they only support the web UI.

**Comment by emsearcy** [comment]
Hi, I saw this as well, but I do not believe the issue is spaces.  The text records in the DNS Made Easy interface have leading and trailing quotes *in the value*.

I believe that when a text record value without these "embedded" quotes is saved on DNS Made Easy, it accepts the change but adds the quotes into the value.

If you add escaped quotes at the beginning and end of your terraform value, DNS records will not attempt to be modified each run (and they still create correctly, too).

```
resource "dme_record" "stitthappens_com_TXT_spf" {
  [...]
  value       = "\"v=spf1 include:_spf.google.com ~all\""
```

That said, perhaps the terraform provider could be smart enough to handle this transform when needed (including when reading from DME), or, documentation could be updated to clarify this.

**Comment by Lupraxus** [comment]
Having exactly the same issue with TXT, A and MX records.

**Comment by emsearcy** [comment]
I also had a related problem with mixed case record values, which is common in TXT records (DKIM) but really a general problem, so maybe it should be its own ticket. In any case the provider is downcasing everything, which isn't necessary; mixed case for values should be supported out to the registrar.

**Comment by nkatarmal-crest** [comment]
Closing this issue, as provider has been redeveloped and released.
